### PR TITLE
By yanniboi: Fix label for user to profile views relationship.

### PR DESCRIPTION
**Pull request by yanniboi**

### CODE REVIEW

**Comment by yanniboi** [comment]
## Before

selection_278

## After

selection_279

**Comment by andrewbelcher** [comment]
@yanniboi worth setting a description while we're at it?

**Comment by yanniboi** [comment]
How did I know you were going to suggest that? :stuck_out_tongue_closed_eyes:

**Comment by yanniboi** [comment]
selection_280

**Comment by andrewbelcher** [comment]
Our ongoing random failure, so will merge anyway.

**Comment by yanniboi** [comment]
:+1:

**Pull request merged**
