### PR TITLE
By yanniboi: Updated Travis config to run different groups of tests o…

### PR DESCRIPTION
**Pull request by yanniboi**
…n pushed and pull requests.

### CODE REVIEW

**Comment by yanniboi** [comment]
The tests are now failing because they are meant to fail. Not because the configuration is off.

**Comment by andrewbelcher** [comment]
It looks like there php unit tests also get run by simpletest, is that expected? Can it be avoided as there is no point running them twice? Also, it's failing to find the registration test... If that's because it's not there, are you having to manually include each one? If they are there then there is a problem of it not finding it.

**Comment by yanniboi** [comment]
It's not finding the registration test because someone merged it into 8.x-1.x with the wrong namespace and my fix is still in a pull request ;) I'll explain the simple test running phpunit tests tomorrow and look into fixing it..

**Comment by andrewbelcher** [comment]
Ok, let's deal with simpletest running phpunit tests as a follow up and I'll merge this in now as it's a big win!

**Pull request merged**
